name: Test

on:
  push:
    paths:
      - "updater/**"
  pull_request:
    paths:
      - "updater/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: updater/go.mod

      - name: Run tests
        working-directory: updater
        run: go test ./...
